upstream cron_ui {
    server pod-a:8080;
    server pod-b:8080;
}

server {
    listen 80;

    location / {
        proxy_pass http://cron_ui;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
